### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by wSedlacek** [nordfjord/nestjs-cqrs-es#1]
Are you planning on doing anything further with this library? I have a few ideas on where this library could be enhanced.

**Comment by nordfjord** [comment]
Hi! I'm currently not planning any further work on this. I ended up copy-pasting the majority of this into the actual project I was working on to be able to evolve it better. The experience of that has convinced me it's probably not a good idea to have a "cqrs/es" framework at all 😂  There's just so many different concerns between projects

The changes I've made so far in that project are:

- Support aggregate snapshots
- Move to the gRPC client of event store
- Got rid of the injectable aggregate repositories in favour of an `AggregateStore` abstraction
- Added a checkpoint store
- Stopped using `nestjs/cqrs` for the buses in favour of a simple "command handler map"
- Got rid of the "Event" class
- Added support for upcasting events
- Added subscription support to the EventStore abstraction

Unfortunately I'm not sure I can share those changes as they are owned by my current employer.

If you want to evolve this project then feel free to copy-paste the code and improve it. I'd be happy to link to your project from this repository

**Comment by wSedlacek** [comment]
Cool! I created a project here where I started to restructure your work.

https://github.com/cqrx/cqrx

Thank you for the ideas not only originally purposed in your blog but also the new ones you shared here.
When I get around to updating the README.md I will credit you and all that.

**Comment by nordfjord** [comment]
Brilliant, I've linked to it in the readme! Good luck!
